# -*- coding: utf-8 -*-
"""train_model_fakenews

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10tQ0ws5Leoagc-KZbCEOAcd3etxIFESs
"""

import pandas as pd 
import numpy as np 
import pickle
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv('train.csv',encoding="ISO-8859-1")
df.columns = ['id','title','text','label']

labels = df.label

X_train, X_test, y_train, y_test = train_test_split(df['text'],labels,test_size=1)

tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)

tfidf_train = tfidf_vectorizer.fit_transform(X_train) 
tfidf_test  = tfidf_vectorizer.transform(X_test)

mnb = MultinomialNB()
mnb.fit(tfidf_train,y_train)

with open('tfidf.pickle','wb') as f:
    pickle.dump(tfidf_vectorizer,f)

with open('m-naivebayes.pickle','wb') as f:
    pickle.dump(mnb,f)